${TARGET}.axf: _frame0.o
${TARGET}.axf: _Frame1.o
${TARGET}.axf: _dict.o
${TARGET}.axf: ladder.o
${TARGET}.axf: imagedata.o
${TARGET}.axf: ladder_dnk_ldx.o
${TARGET}.axf: ${ROOT}/lib/TPD-280/startup_gcc.o
${TARGET}.axf: ${ROOT}/lib/TPD-280.a
${TARGET}.axf: ${ROOT}/lib/common.a
${TARGET}.axf: ${ROOT}/lib/libgrw.a
${TARGET}.axf: ${ROOT}/lib/fonts.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_cs_latin1s.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_cyrillic.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_french.a
${TARGET}.axf: ${ROOT}/lib/font_icpdas_rc_latin1s.a
${TARGET}.axf: ${ROOT}/lib/libdriver.a
